-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, CONCAT(U.CITY, U.STREET_ADDRESS1, U.STREET_ADDRESS2) AS '전체주소', CONCAT(SUBSTRING(U.TLNO,1,3),'-',SUBSTRING(U.TLNO,4,4),'-',SUBSTRING(U.TLNO,8)) AS '전화번호'
FROM (SELECT COUNT(B.WRITER_ID)>=3 AS WRITER_ID FROM USED_GOODS_BOARD B) BB
JOIN USED_GOODS_USER U ON U.USER_ID = BB.WRITER_ID
-- WHERE SUM(B.WRITER_ID) >= 3
-- GROUP BY B.WRITER_ID
ORDER BY U.USER_ID