-- 코드를 입력하세요
SELECT YEAR(U.SALES_DATE) YEAR, MONTH(U.SALES_DATE) MONTH, U.GENDER, COUNT(U.USER_ID) USERS
FROM (SELECT A.USER_ID, A.GENDER, O.SALES_DATE FROM USER_INFO A JOIN ONLINE_SALE O ON O.USER_ID = A.USER_ID WHERE A.USER_ID = O.USER_ID GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE),
O.USER_ID ) U

WHERE U.GENDER IS NOT NULL 
GROUP BY YEAR, MONTH, U.GENDER
ORDER BY YEAR, MONTH, U.GENDER
