-- 코드를 입력하세요

SELECT  YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH,
        COUNT(DISTINCT S.USER_ID) AS PUCHASED_USERS, 
        ROUND(COUNT(DISTINCT S.USER_ID)/(SELECT COUNT(USER_ID)FROM USER_INFO         WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE S
JOIN USER_INFO U ON U.USER_ID = S.USER_ID
WHERE YEAR(U.JOINED) ='2021' #AND S.USER_ID IN (SELECT USER_ID FROM ONLINE_SALE) 
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
