-- 코드를 입력하세요

SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, COUNT(U.USER_ID) AS PUCHASED_USERS, 
# (COUNT(YEAR(U.JOINED) ='2021' AND U.USER_ID IN (SELECT USER_ID FROM ONLINE_SALE)))/ (COUNT YEAR(U.JOINED) ='2021') 
# AS PUCHASED_RATIO
ROUND(COUNT(DISTINCT S.USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(U.JOINED) = 2021), 1) AS PUCHASED_RATIO

#COUNT(연월별 상품을 구매한 회원 수) AS PUCHASED_USERS, 
#COUNT(YEAR(U.JOINED) ='2021' AND U.USER_ID IN (SELECT USER_ID FROM ONLINE_SALE) / PUCHASED_USERS) AS PUCHASED_RATIO
#상품 구매한 회원 비율 ROUND,1
# (2021년에 가입한 회원 중 상품을 구매한 회원수= (COUNT YEAR(U.JOINED) ='2021')
#  / 2021년에 가입한 전체 회원 수)) AS PUCHASED_RATIO
#COUNT(YEAR(U.JOINED) ='2021' AND U.USER_ID IN (SELECT USER_ID FROM ONLINE_SALE))/ (COUNT YEAR(U.JOINED) ='2021') AS PUCHASED_RATIO
FROM ONLINE_SALE S
JOIN USER_INFO U ON U.USER_ID = S.USER_ID
WHERE YEAR(U.JOINED) ='2021' AND U.USER_ID IN (SELECT USER_ID FROM ONLINE_SALE) 
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH

# JOIN (SELECT USER_ID, JOINED FROM USER_INFO WHERE YEAR(JOINED = '2021') U 
# ON U.USER_ID = S.USER_ID