-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD, A.APNT_CNCL_YN
JOIN APPOINTMENT A ON A.PT_NO = P.PT_NO
JOIN DOCTOR D ON D.MCDP_CD = A.MCDP_CD
-- WHERE A.APNT_CNCL_YN='N'