SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM DOCTOR D
JOIN (SELECT APNT_NO, PT_NO, MCDP_CD,MDDR_ID, APNT_YMD, APNT_CNCL_YN FROM APPOINTMENT WHERE MCDP_CD = 'CS' AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND APNT_CNCL_YN ='N') A
ON D.DR_ID = A.MDDR_ID
JOIN PATIENT P ON P.PT_NO = A.PT_NO
ORDER BY A.APNT_YMD 


