-- 코드를 입력하세요
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID IN
(SELECT R2.MEMBER_ID
FROM (SELECT R.MEMBER_ID, RANK() OVER (ORDER BY count(R.MEMBER_ID) DESC) AS RNK FROM REST_REVIEW R GROUP BY R.MEMBER_ID) R2
WHERE RNK = 1)
#GROUP BY R2.MEMBER_ID
#WHERE RNK =1)
#RANK() OVER (ORDER BY count(R.MEMBER_ID) DESC) AS RNK)
# GROUP BY R.MEMBER_ID)
     # GROUP BY R.MEMBER_ID)
#WHERE RNK = 1 
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT


# SELECT M.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
# FROM MEMBER_PROFILE M
# JOIN REST_REVIEW R ON R.MEMBER_ID = M.MEMBER_ID
# WHERE R.MEMBER_ID IN
#     (SELECT R.MEMBER_ID #, count(R.MEMBER_ID) AS CNT
#      FROM REST_REVIEW R 
#      RANK() OVER (ORDER BY count(R.MEMBER_ID) DESC) AS RNK)
#      # GROUP BY R.MEMBER_ID)
#      # WHERE RNK = 1 
# ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT