-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) >=08 AND MONTH(START_DATE) <=10
GROUP BY CAR_ID
HAVING RECORDS >= 5 AND RECORDS != 0
ORDER BY MONTH ASC, CAR_ID DESC